[package]
name = "openpty"
version = "0.1.0"
authors = ["Milkey Mouse <milkeymouse@meme.institute>"]
edition = "2018"
description = "Rust implementation of libc openpty()"
license = "MIT OR Apache-2.0"

[dependencies]
libc = "0.2.49"
nix = "0.13.0"
